language: minimal
before_deploy:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)-$TRAVIS_COMMIT_MESSAGE}
- git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
- ls -R
script:
- "chmod +x ./build.sh"
- "./build.sh A17"
deploy:
  provider: releases
  api_key:
    secure: 7Tw3MmnHoqTP4Kg3srJzZr2VOkaRZ6Vr+6YWDQzcjH+TNDcUF67gF3mnN6v/EKZU/1VEBVYqaan2ZGbvXoAoFazRoZboD4qNSYhHJmhYa+ZGg+FvL4+ual0Ca+8uECfcC4bWypfOTLfu7mLZzP3CSjRD9n2539EdxulFSeQdaVMtdXH6r6INGuaQQSNRMP9POCtN2hCm6kwNu+vE7TemQBUUFObH7iKCvQ7rUXdEqQkZ1dnQUkNhy6jOeE9A0NJsQ73T/R9k8izC7ZBCDGYzO34r/bQlQaSoazUlXXR36EoFp4JVYNQcgRCJTWwKYuyP6dRIJphIlMWdEOJmhXGbud3UJas75O+gQdTKcLR7WslLV/b+s52LrZViICwX9w1XS1UaRDImV0jC83/mkgtpPmmKCr3xkzoSFRvSwf02QW4A6w1uwdAoUvi3yXiOK55GpqYasWwHpHbJdMmf6uaTnccVRa2oiGYhELYS/tCqOxoSk7ZNdR/rlz5eTqY/0f6LbfIMVxdNcrzSRDFCD2Cd8z2SVxc0C+d66fAYO4GynV0rYjzsHjX6p62QBO7b8g6+PkgElKU9lZzsFDKtiwOZzom9qUphGIWBibpnCZE6YKjefcj/LxxZIOPfDUR5aP+Uz4U0FEaKoIrNXLbEWol8DYKR+kkUXeTbezJLrlPwJuo=
  file: dist/sdtdIcons - A17.tar.gz
  on:
    tags: true
    branch: master