name: Release

on:
  push:
    # branches to consider in the event; optional, defaults to all
#    branches:
#      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: ./build.sh

      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "latest"
          message: "Latest release"

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: latest
          draft: false
          prerelease: false
          generate_release_notes: false
          files: |
            dist/sdtdIcons.tar.gz
